spring.application.name=ecomerskafka

spring.output.ansi.enabled=ALWAYS
spring.devtools.add-properties=true
logging.level.web=DEBUG
spring.main.banner-mode=log
spring.thymeleaf.cache=false

## Configuracion del puerto
server.port=9000

## Configuracion de logs
logging.level.root=INFO
logging.level.mx.com.gm=DEBUG
logging.pattern.dateformat=hh:mm

